[build]
     publish = "build"
     command = "npm run build"

   [[plugins]]
     package = "netlify-plugin-password-protection"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"  